version: '3'

services:
  ui:
    build: client
    depends_on:
      - 'database'
    ports:
      - '8080:8080'

  api:
    build: server
    depends_on:
      - 'database'
    ports:
      - '8080:8080'

  database:
    image: postgres:latest